export const ProjectDatas = [
    {
        id: 1,
        name: "Local RAG System (AI Pipeline)",
        des: "Fully local RAG system using Ollama (Gemma) + ChromaDB. Processes PDFs, performs semantic vector search, generates context-aware responses — zero external API dependency.",
        tags: ["Ollama", "ChromaDB", "RAG", "LLMOps", "Python", "Vector Embeddings"],
        button: "GitHub",
        url: 'https://github.com/VikyHari',
        accent: "purple",
        icon: "fa-solid fa-brain",
    },
    {
        id: 2,
        name: "Learning Management System (LMS)",
        des: "Full-featured LMS for CDP360 with dynamic course management, responsive UI, and real-time student progress tracking. Deployed at scale.",
        tags: ["React.js", "JavaScript", "SASS", "Bootstrap", "REST APIs"],
        button: "Live Demo",
        url: 'http://edu.cdp360.org/',
        accent: "cyan",
        icon: "fa-solid fa-graduation-cap",
    },
    {
        id: 3,
        name: "NEET/JEE Coaching Platform",
        des: "Landing page and coaching platform for India's NEET/JEE competitive exam preparation. Mobile-first design with animated UI, served at production scale.",
        tags: ["React.js", "JavaScript", "SASS", "Responsive Design"],
        button: "Live Demo",
        url: 'https://neetjeecoaching.cdp360.org/',
        accent: "pink",
        icon: "fa-solid fa-atom",
    },
    {
        id: 4,
        name: "CDP360 Corporate Website",
        des: "Corporate landing page for CDP360 — clean, fast, fully responsive design with modern sections and smooth animations.",
        tags: ["HTML", "CSS", "Bootstrap", "Responsive Design"],
        button: "Live Demo",
        url: 'https://cdp360.org/',
        accent: "green",
        icon: "fa-solid fa-globe",
    },
    {
        id: 5,
        name: "LMS Android App",
        des: "Mobile companion app for the LMS with NEET/JEE mock tests, course access, and offline-ready features built with React Native.",
        tags: ["React Native", "JavaScript", "Android", "Mobile UI"],
        button: "Play Store",
        url: 'https://play.google.com/store/apps/details?id=com.cdp360.app&hl=en',
        accent: "purple",
        icon: "fa-brands fa-android",
    },
    {
        id: 6,
        name: "Node.js REST API — Contacts",
        des: "Backend REST API for contact management with full CRUD, MongoDB storage, Express routing and field validation.",
        tags: ["Node.js", "Express", "MongoDB", "REST API"],
        button: "GitHub",
        url: 'https://github.com/VikyHari/nodejs-contact-Backend',
        accent: "cyan",
        icon: "fa-brands fa-node-js",
    },
    {
        id: 7,
        name: "EduConnect — Education Platform",
        des: "Collaborative online education platform enabling students and teachers to share study materials, conduct live sessions, manage assignments, and track progress in real time.",
        tags: ["Next.js", "React.js", "WebRTC", "Tailwind CSS", "Node.js", "Live Streaming"],
        button: "GitHub",
        url: 'https://github.com/VikyHari',
        accent: "cyan",
        icon: "fa-solid fa-chalkboard-user",
    },
    {
        id: 8,
        name: "Startup Hire — Recruitment Platform",
        des: "Smart recruitment platform connecting startups with skilled professionals using intelligent job matching, applicant management systems, and analytics dashboards.",
        tags: ["Next.js", "React.js", "Redux", "Node.js", "MongoDB", "REST APIs"],
        button: "GitHub",
        url: 'https://github.com/VikyHari',
        accent: "purple",
        icon: "fa-solid fa-briefcase",
    },
    {
        id: 9,
        name: "NEET/JEE Online Mock Test",
        des: "Online examination platform for NEET & JEE aspirants with timed tests, real-time scoring, performance analytics, and detailed result reports.",
        tags: ["React.js", "Firebase", "Chart.js", "JavaScript", "Performance Analytics"],
        button: "Live Demo",
        url: 'https://neetjeecoaching.cdp360.org/',
        accent: "green",
        icon: "fa-solid fa-clipboard-question",
    },
]
